2025-01-28 21:31:33,800 - INFO - Found 3 keywords to process
2025-01-28 21:31:33,800 - INFO - Keywords: ['Longevity', 'Type_1_Diabetes', 'Type_2_Diabetes']
2025-01-28 21:31:33,800 - INFO - Resuming from checkpoint: i=0, j=0
2025-01-28 21:31:33,802 - INFO - 
Processing trait (1/3): Longevity
2025-01-28 21:31:33,802 - INFO - Search query: (30:10000[Number of Samples]) AND ("Homo sapiens"[Organism]) AND (2010:2025[Publication Date]) AND (Longevity) AND ("expression profiling by array"[DataSet Type] OR "expression profiling by high throughput sequencing"[DataSet Type] OR "genome variation profiling by high throughput sequencing"[DataSet Type] OR "genome variation profiling by snp array"[DataSet Type] OR "snp genotyping by snp array"[DataSet Type] OR "third party reanalysis"[DataSet Type])
2025-01-28 21:31:34,622 - INFO - Total results for query: 10
2025-01-28 21:31:34,623 - INFO - Fetching batch 1 of 1 (size: 10)
2025-01-28 21:31:34,966 - INFO - Successfully retrieved 10 IDs in batch 1
2025-01-28 21:31:34,967 - INFO - Found 10 datasets for: Longevity
2025-01-28 21:32:09,589 - ERROR - Error processing dataset 200205101: Remote end closed connection without response
Traceback (most recent call last):
  File "/home/techt/Desktop/GenoAgent/download/download_GEO_data.py", line 228, in get_GEO_series_access
    dataset_handle = Entrez.esummary(db="gds", id=dataset_id)
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/site-packages/Bio/Entrez/__init__.py", line 345, in esummary
    return _open(request)
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/site-packages/Bio/Entrez/__init__.py", line 634, in _open
    handle = urlopen(request)
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/techt/anaconda3/envs/agent/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

